using Microsoft.EntityFrameworkCore;
using PersonalUltra.Domain;

namespace PersonalUltra.Infrastructure;

public sealed class PersonalUltraDbContext(DbContextOptions<PersonalUltraDbContext> options) : DbContext(options)
{
    public DbSet<Trainer> Trainers => Set<Trainer>();
    public DbSet<TrainerBranding> TrainerBrandings => Set<TrainerBranding>();
    public DbSet<TrainerPrescriptionSettings> TrainerPrescriptionSettings => Set<TrainerPrescriptionSettings>();
    public DbSet<Student> Students => Set<Student>();
    public DbSet<TrainerStudent> TrainerStudents => Set<TrainerStudent>();
    public DbSet<StudentInvite> StudentInvites => Set<StudentInvite>();
    public DbSet<Anamnesis> Anamneses => Set<Anamnesis>();
    public DbSet<TrainerMessage> TrainerMessages => Set<TrainerMessage>();
    public DbSet<Exercise> Exercises => Set<Exercise>();
    public DbSet<WorkoutTemplate> WorkoutTemplates => Set<WorkoutTemplate>();
    public DbSet<WorkoutTemplateExercise> WorkoutTemplateExercises => Set<WorkoutTemplateExercise>();
    public DbSet<StudentWorkout> StudentWorkouts => Set<StudentWorkout>();
    public DbSet<StudentWorkoutExercise> StudentWorkoutExercises => Set<StudentWorkoutExercise>();
    public DbSet<WorkoutSession> WorkoutSessions => Set<WorkoutSession>();
    public DbSet<WorkoutSessionExercise> WorkoutSessionExercises => Set<WorkoutSessionExercise>();
    public DbSet<SetPerformance> SetPerformances => Set<SetPerformance>();
    public DbSet<NutritionPlan> NutritionPlans => Set<NutritionPlan>();
    public DbSet<Meal> Meals => Set<Meal>();
    public DbSet<MealFood> MealFoods => Set<MealFood>();
    public DbSet<MealFoodAlternative> MealFoodAlternatives => Set<MealFoodAlternative>();
    public DbSet<NutritionTemplate> NutritionTemplates => Set<NutritionTemplate>();
    public DbSet<NutritionTemplateMeal> NutritionTemplateMeals => Set<NutritionTemplateMeal>();
    public DbSet<NutritionTemplateFood> NutritionTemplateFoods => Set<NutritionTemplateFood>();
    public DbSet<NutritionTemplateFoodAlternative> NutritionTemplateFoodAlternatives => Set<NutritionTemplateFoodAlternative>();
    public DbSet<WeightEntry> WeightEntries => Set<WeightEntry>();
    public DbSet<HydrationEntry> HydrationEntries => Set<HydrationEntry>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("public");
        modelBuilder.Entity<Trainer>(entity => { entity.ToTable("trainers", "core"); entity.HasKey(x => x.Id); entity.Property(x => x.Name).HasMaxLength(200); });
        modelBuilder.Entity<TrainerBranding>(entity => { entity.ToTable("trainer_brandings", "core"); entity.HasKey(x => x.Id); entity.Property(x => x.DisplayName).HasMaxLength(200); entity.Property(x => x.PrimaryColor).HasMaxLength(20); entity.Property(x => x.LogoUrl).HasMaxLength(2000); entity.HasIndex(x => x.TrainerId).IsUnique(); entity.HasOne(x => x.Trainer).WithOne(x => x.Branding).HasForeignKey<TrainerBranding>(x => x.TrainerId); });
        modelBuilder.Entity<TrainerPrescriptionSettings>(entity => { entity.ToTable("trainer_prescription_settings", "training"); entity.HasKey(x => x.Id); entity.HasIndex(x => x.TrainerId).IsUnique(); entity.HasOne(x => x.Trainer).WithOne(x => x.PrescriptionSettings).HasForeignKey<TrainerPrescriptionSettings>(x => x.TrainerId); });
        modelBuilder.Entity<Student>(entity => { entity.ToTable("students", "core"); entity.HasKey(x => x.Id); entity.Property(x => x.FirstName).HasMaxLength(100); entity.Property(x => x.LastName).HasMaxLength(100); entity.Property(x => x.Email).HasMaxLength(320); entity.Property(x => x.Phone).HasMaxLength(16); entity.Property(x => x.PreferredName).HasMaxLength(100); entity.HasIndex(x => x.Email).IsUnique(); });
        modelBuilder.Entity<TrainerStudent>(entity => { entity.ToTable("trainer_students", "core"); entity.HasKey(x => x.Id); entity.HasIndex(x => new { x.TrainerId, x.StudentId }).IsUnique(); entity.HasOne(x => x.Trainer).WithMany(x => x.Students).HasForeignKey(x => x.TrainerId); entity.HasOne(x => x.Student).WithMany(x => x.Trainers).HasForeignKey(x => x.StudentId); });
        modelBuilder.Entity<StudentInvite>(entity => { entity.ToTable("student_invites", "core"); entity.HasKey(x => x.Id); entity.Property(x => x.Token).HasMaxLength(200); entity.Property(x => x.InviteCode).HasMaxLength(6); entity.Property(x => x.Email).HasMaxLength(320); entity.HasIndex(x => x.Token).IsUnique(); entity.HasIndex(x => x.InviteCode).IsUnique(); entity.HasOne(x => x.Trainer).WithMany(x => x.Invites).HasForeignKey(x => x.TrainerId); });
        modelBuilder.Entity<Anamnesis>(entity => { entity.ToTable("anamneses", "core"); entity.HasKey(x => x.Id); entity.Property(x => x.AnswersJson).HasColumnType("jsonb"); entity.HasIndex(x => x.StudentId).IsUnique(); entity.HasOne(x => x.Student).WithOne(x => x.Anamnesis).HasForeignKey<Anamnesis>(x => x.StudentId); });
        modelBuilder.Entity<TrainerMessage>(entity => { entity.ToTable("trainer_messages", "engagement"); entity.HasKey(x => x.Id); entity.Property(x => x.Message).HasMaxLength(1000); entity.HasOne(x => x.Trainer).WithMany(x => x.Messages).HasForeignKey(x => x.TrainerId); entity.HasOne(x => x.Student).WithMany(x => x.Messages).HasForeignKey(x => x.StudentId); entity.HasIndex(x => new { x.StudentId, x.StartsAt }); });
        modelBuilder.Entity<Exercise>(entity => { entity.ToTable("exercises", "training"); entity.HasKey(x => x.Id); entity.Property(x => x.Name).HasMaxLength(200); entity.Property(x => x.Slug).HasMaxLength(200); entity.Property(x => x.PrimaryMuscleGroup).HasMaxLength(100); entity.Property(x => x.Equipment).HasMaxLength(100); entity.Property(x => x.ImageRef).HasMaxLength(2000); entity.Property(x => x.Instructions).HasMaxLength(4000); entity.Property(x => x.DefaultTrackingMode).HasMaxLength(32).HasDefaultValue(ExerciseTrackingModes.Repetitions); entity.Property(x => x.IsActive).HasDefaultValue(true); entity.HasIndex(x => x.Slug).IsUnique(); entity.HasIndex(x => new { x.IsActive, x.PrimaryMuscleGroup }); });
        modelBuilder.Entity<WorkoutTemplate>(entity => { entity.ToTable("workout_templates", "training"); entity.HasKey(x => x.Id); entity.Property(x => x.Name).HasMaxLength(200); entity.Property(x => x.Notes).HasMaxLength(2000); entity.HasOne(x => x.Trainer).WithMany().HasForeignKey(x => x.TrainerId); });
        modelBuilder.Entity<WorkoutTemplateExercise>(entity => { entity.ToTable("workout_template_exercises", "training"); entity.HasKey(x => x.Id); entity.Property(x => x.TrackingMode).HasMaxLength(32).HasDefaultValue(ExerciseTrackingModes.Repetitions); entity.Property(x => x.Notes).HasMaxLength(1000); entity.HasIndex(x => new { x.WorkoutTemplateId, x.Sequence }).IsUnique(); entity.HasOne(x => x.WorkoutTemplate).WithMany(x => x.Exercises).HasForeignKey(x => x.WorkoutTemplateId); entity.HasOne(x => x.Exercise).WithMany().HasForeignKey(x => x.ExerciseId).OnDelete(DeleteBehavior.Restrict); });
        modelBuilder.Entity<StudentWorkout>(entity => { entity.ToTable("student_workouts", "training"); entity.HasKey(x => x.Id); entity.Property(x => x.Name).HasMaxLength(200); entity.Property(x => x.Notes).HasMaxLength(2000); entity.Property(x => x.IsActive).HasDefaultValue(true); entity.HasIndex(x => new { x.StudentId, x.IsActive }); entity.HasIndex(x => new { x.StudentId, x.SuggestedOrder }).IsUnique().HasFilter("\"IsActive\""); entity.HasOne(x => x.Trainer).WithMany().HasForeignKey(x => x.TrainerId); entity.HasOne(x => x.Student).WithMany().HasForeignKey(x => x.StudentId); });
        modelBuilder.Entity<StudentWorkoutExercise>(entity => { entity.ToTable("student_workout_exercises", "training"); entity.HasKey(x => x.Id); entity.Property(x => x.Name).HasMaxLength(200); entity.Property(x => x.PrimaryMuscleGroup).HasMaxLength(100); entity.Property(x => x.Equipment).HasMaxLength(100); entity.Property(x => x.ImageRef).HasMaxLength(2000); entity.Property(x => x.Instructions).HasMaxLength(4000); entity.Property(x => x.TrackingMode).HasMaxLength(32).HasDefaultValue(ExerciseTrackingModes.Repetitions); entity.Property(x => x.Notes).HasMaxLength(1000); entity.HasIndex(x => new { x.StudentWorkoutId, x.Sequence }).IsUnique(); entity.HasOne(x => x.StudentWorkout).WithMany(x => x.Exercises).HasForeignKey(x => x.StudentWorkoutId); entity.HasOne(x => x.Exercise).WithMany().HasForeignKey(x => x.ExerciseId).OnDelete(DeleteBehavior.Restrict); });
        modelBuilder.Entity<WorkoutSession>(entity => { entity.ToTable("workout_sessions", "training"); entity.HasKey(x => x.Id); entity.Property(x => x.Status).HasMaxLength(32); entity.HasOne(x => x.Student).WithMany().HasForeignKey(x => x.StudentId); entity.HasOne(x => x.StudentWorkout).WithMany(x => x.Sessions).HasForeignKey(x => x.StudentWorkoutId); });
        modelBuilder.Entity<WorkoutSessionExercise>(entity => { entity.ToTable("workout_session_exercises", "training"); entity.HasKey(x => x.Id); entity.Property(x => x.Name).HasMaxLength(200); entity.Property(x => x.PrimaryMuscleGroup).HasMaxLength(100); entity.Property(x => x.Equipment).HasMaxLength(100); entity.Property(x => x.ImageRef).HasMaxLength(2000); entity.Property(x => x.Instructions).HasMaxLength(4000); entity.Property(x => x.TrackingMode).HasMaxLength(32).HasDefaultValue(ExerciseTrackingModes.Repetitions); entity.Property(x => x.Notes).HasMaxLength(1000); entity.HasOne(x => x.WorkoutSession).WithMany(x => x.Exercises).HasForeignKey(x => x.WorkoutSessionId); entity.HasOne(x => x.Exercise).WithMany().HasForeignKey(x => x.ExerciseId).OnDelete(DeleteBehavior.Restrict); });
        modelBuilder.Entity<SetPerformance>(entity => { entity.ToTable("set_performances", "training"); entity.HasKey(x => x.Id); entity.Property(x => x.ClientOperationId).HasMaxLength(200); entity.Property(x => x.WeightKg).HasPrecision(7, 2); entity.HasIndex(x => new { x.WorkoutSessionExerciseId, x.SetNumber }).IsUnique(); entity.HasIndex(x => new { x.WorkoutSessionExerciseId, x.ClientOperationId }).IsUnique(); entity.HasOne(x => x.WorkoutSessionExercise).WithMany(x => x.Performances).HasForeignKey(x => x.WorkoutSessionExerciseId); });
        modelBuilder.Entity<NutritionPlan>(entity => { entity.ToTable("nutrition_plans", "nutrition"); entity.HasKey(x => x.Id); entity.Property(x => x.Name).HasMaxLength(200); entity.Property(x => x.Notes).HasMaxLength(2000); entity.Property(x => x.DailyCalories).HasPrecision(7, 0); entity.Property(x => x.DailyProteinGrams).HasPrecision(7, 1); entity.Property(x => x.DailyCarbohydratesGrams).HasPrecision(7, 1); entity.Property(x => x.DailyFatGrams).HasPrecision(7, 1); entity.HasOne(x => x.Trainer).WithMany().HasForeignKey(x => x.TrainerId).OnDelete(DeleteBehavior.Restrict); entity.HasOne(x => x.CreatedByTrainer).WithMany().HasForeignKey(x => x.CreatedByTrainerId).OnDelete(DeleteBehavior.Restrict); entity.HasOne(x => x.UpdatedByTrainer).WithMany().HasForeignKey(x => x.UpdatedByTrainerId).OnDelete(DeleteBehavior.Restrict); entity.HasOne<Student>().WithMany().HasForeignKey(x => x.StudentId); entity.HasIndex(x => x.StudentId).IsUnique(); });
        modelBuilder.Entity<Meal>(entity => { entity.ToTable("meals", "nutrition"); entity.HasKey(x => x.Id); entity.Property(x => x.Name).HasMaxLength(200); entity.Property(x => x.Notes).HasMaxLength(1000); entity.HasIndex(x => new { x.NutritionPlanId, x.Sequence }).IsUnique(); entity.HasOne(x => x.NutritionPlan).WithMany(x => x.Meals).HasForeignKey(x => x.NutritionPlanId); });
        modelBuilder.Entity<MealFood>(entity => { entity.ToTable("meal_foods", "nutrition"); entity.HasKey(x => x.Id); entity.Property(x => x.FoodName).HasMaxLength(200); entity.Property(x => x.Quantity).HasPrecision(7, 2); entity.Property(x => x.Unit).HasMaxLength(40); entity.HasIndex(x => new { x.MealId, x.Sequence }).IsUnique(); entity.HasOne(x => x.Meal).WithMany(x => x.Foods).HasForeignKey(x => x.MealId); });
        modelBuilder.Entity<MealFoodAlternative>(entity => { entity.ToTable("meal_food_alternatives", "nutrition"); entity.HasKey(x => x.Id); entity.Property(x => x.FoodName).HasMaxLength(200); entity.Property(x => x.Quantity).HasPrecision(7, 2); entity.Property(x => x.Unit).HasMaxLength(40); entity.Property(x => x.Notes).HasMaxLength(1000); entity.HasIndex(x => new { x.MealFoodId, x.Sequence }).IsUnique(); entity.HasOne(x => x.MealFood).WithMany(x => x.Alternatives).HasForeignKey(x => x.MealFoodId).OnDelete(DeleteBehavior.Cascade); });
        modelBuilder.Entity<NutritionTemplate>(entity => { entity.ToTable("nutrition_templates", "nutrition"); entity.HasKey(x => x.Id); entity.Property(x => x.Name).HasMaxLength(200); entity.Property(x => x.Notes).HasMaxLength(2000); entity.HasIndex(x => new { x.TrainerId, x.Name }); entity.HasOne(x => x.Trainer).WithMany().HasForeignKey(x => x.TrainerId).OnDelete(DeleteBehavior.Restrict); });
        modelBuilder.Entity<NutritionTemplateMeal>(entity => { entity.ToTable("nutrition_template_meals", "nutrition"); entity.HasKey(x => x.Id); entity.Property(x => x.Name).HasMaxLength(200); entity.Property(x => x.Notes).HasMaxLength(1000); entity.HasIndex(x => new { x.NutritionTemplateId, x.Sequence }).IsUnique(); entity.HasOne(x => x.NutritionTemplate).WithMany(x => x.Meals).HasForeignKey(x => x.NutritionTemplateId); });
        modelBuilder.Entity<NutritionTemplateFood>(entity => { entity.ToTable("nutrition_template_foods", "nutrition"); entity.HasKey(x => x.Id); entity.Property(x => x.FoodName).HasMaxLength(200); entity.Property(x => x.Quantity).HasPrecision(7, 2); entity.Property(x => x.Unit).HasMaxLength(40); entity.HasIndex(x => new { x.NutritionTemplateMealId, x.Sequence }).IsUnique(); entity.HasOne(x => x.Meal).WithMany(x => x.Foods).HasForeignKey(x => x.NutritionTemplateMealId); });
        modelBuilder.Entity<NutritionTemplateFoodAlternative>(entity => { entity.ToTable("nutrition_template_food_alternatives", "nutrition"); entity.HasKey(x => x.Id); entity.Property(x => x.FoodName).HasMaxLength(200); entity.Property(x => x.Quantity).HasPrecision(7, 2); entity.Property(x => x.Unit).HasMaxLength(40); entity.Property(x => x.Notes).HasMaxLength(1000); entity.HasIndex(x => new { x.NutritionTemplateFoodId, x.Sequence }).IsUnique(); entity.HasOne(x => x.Food).WithMany(x => x.Alternatives).HasForeignKey(x => x.NutritionTemplateFoodId).OnDelete(DeleteBehavior.Cascade); });
        modelBuilder.Entity<WeightEntry>(entity => { entity.ToTable("weight_entries", "progress"); entity.HasKey(x => x.Id); entity.Property(x => x.WeightKg).HasPrecision(6, 2); entity.HasOne(x => x.Student).WithMany().HasForeignKey(x => x.StudentId); entity.HasIndex(x => new { x.StudentId, x.RecordedAt }); });
        modelBuilder.Entity<HydrationEntry>(entity => { entity.ToTable("hydration_entries", "progress"); entity.HasKey(x => x.Id); entity.Property(x => x.AmountMl).IsRequired(); entity.HasOne(x => x.Student).WithMany().HasForeignKey(x => x.StudentId); entity.HasIndex(x => new { x.StudentId, x.RecordedAt }); });
    }
}
